name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  UV_VERSION: "0.3.1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.12"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Set up uv
      run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

    - name: Basic smoke test
      run: uv run IC_filtering.py --help
